---
title: "Individual-level analysis: simple models"
subtitle: "Part of the final project for AQMSS II"
author: "Polikanov Stepan and Okisheva Vera"
format:
  pdf:
    fig-pos: "H"
    fontsize: 11pt
    highlight-style: kate
    fig-width: 10
    fig-height: 6
    include-in-header:
      - text: |
          \addtokomafont{disposition}{\rmfamily} 
          \AddToHook{env/Highlighting/begin}{\scriptsize} 
          \usepackage{float} 
          \usepackage[backend = biber, style = apa]{biblatex}
embed-resources: true
execute: 
  echo: true
  warning: false
  error: false
  message: false
---

```{r}
#| label: setup
#| cache: false

source(here::here("utilities", "check_packages.R"))
source(here::here("utilities", "functions.R"))

conflicts_prefer(dplyr::filter)
```

```{r}
#| label: load-data

ep_raw_dep <- read_rds(here("data", "data_built", "ep_raw_dep.rds"))
data_country <- read_rds(here("data", "data_built", "data_country.rds"))
```

```{r}
#| label: prep-naive

# Recode no data back to native NA
model_data <- ep_raw_dep |> 
  mutate(across(c(sex, age_bin, time_to_vs.less_than_hour, 
                  time_to_vs.less_than_hour, out_of_Russia_time, 
                  result_trust_bin), 
                ~ if_else(. %in% c("No Data", "Declined to answer"), NA, .)),
         vote = relevel(as.factor(vote), ref = "Putin"),
         sex = relevel(as.factor(sex), ref = "Male"),
         age_bin = relevel(as.factor(age_bin), ref = "25-44"),
         out_of_Russia_time = relevel(as.factor(out_of_Russia_time), ref = "Before annexation"),
         result_trust_bin = relevel(as.factor(result_trust_bin), ref = "Yes")) |> 
  filter(!countryname_en %in% c("New Zealand", "Australia"))
```

```{r}
#| label: prep-coefficient-labels

coef_map_default <- c("(Intercept)", "sexFemale" = "Sex: Female", 
                      "sexOther" = "Sex: Other", 
                      "age_bin18-24" = "Age: 18-24 (ref 25-44)", 
                      "age_bin45-64" = "Age: 45-65 (ref 25-44)", 
                      "age_bin65+" = "Age: 65 + (ref 25-44)", 
                      "time_to_vs.less_than_hourYes" = 
                        "Took < 1 hour to get to the voting station",
                      "out_of_Russia_timeAfter invasion" = 
                        "Moved after March 2022 (ref before 2014)", 
                      "out_of_Russia_time2 - 5 years" = 
                        paste("Moved after March 2019 but before",
                              "March 2022 (ref before 2014)"),
                      "out_of_Russia_timeAfter annexation" =
                        paste("Moved after March 2014 but before",
                              "March 2019 (ref before 2014)"),
                      "out_of_Russia_timeTourist (lives in Russia)" =
                        paste("Didn't move - tourist, lives",
                              "in Russia (ref before 2014)"),
                      "result_trust_binDon't know" = 
                        "Trust in the result: Don't know (ref Yes)",
                      "result_trust_binNo" = 
                        "Trust in the result: No (ref Yes)")
```


```{r}
#| label: tbl-linear-dummy
#| tbl-cap: "Binary outcomes, linear models, naive approach"
#| results: asis

model_data |> 
  pivot_longer(cols = c(vote_putin, vote_declined, vote_putin_declined,
                        vote_davankov, vote_spoiled, vote_opposition)) |> 
  nest(data = -name) |> 
  transmute(m1.naive = map(data, 
                        ~ lm(value ~ sex + age_bin + time_to_vs.less_than_hour
                             + out_of_Russia_time + result_trust_bin,
                             data = .))) |> 
  deframe() |> 
  set_names(c("Vote Putin", "Decline to Answer", "Putin or Declined", 
              "Vote Davankov", "Spoil the ballot", "Vote Davankov or spoil")) |>
  modelsummary(output = "kableExtra", vcov = "robust", stars = T,
               gof_map = c("nobs", "adj.r.squared", "bic", "logLik", "rmse"),
               coef_map = coef_map_default) |> 
  kable_styling(latex_options = c("scale_down"))
```

# Multinomial

```{r}
#| label: models-multinom-naive
#| results: hide
#| cache: true

m2.naive <- multinom(vote ~ sex + age_bin + time_to_vs.less_than_hour
                     + out_of_Russia_time + result_trust_bin, 
                     data = model_data, model = F)
```

```{r}
#| label: models-multinom-fe
#| results: hide
#| cache: true

m2.fe <- multinom(vote ~ sex + age_bin + time_to_vs.less_than_hour
                  + out_of_Russia_time + result_trust_bin
                  + as.factor(voting_station), 
                  data = model_data, model = F)
```

```{r}
#| label: tbl-multinom-naive
#| tbl-cap: "Multinomial regression, naive approach"
#| cache: true
#| dependson: models-multinom-naive

modelsummary(list("Naive approach" = m2.naive), 
             output = "kableExtra",
             stars = T, shape = term ~ response, 
             coef_map = coef_map_default, 
             gof_map = c("nobs", "adj.r.squared", "bic", "rmse")) |> 
  kable_styling(latex_options = c("scale_down"))
```

```{r}
#| label: tbl-multinom-fe
#| tbl-cap: "Multinomial regression, fixed effects"
#| cache: true
#| dependson: models-multino3m-fe

gc()

modelsummary(list("Fixed Effects" = m2.fe),  
             output = "kableExtra",
             stars = T, shape = term ~ response, 
             coef_map = coef_map_default, 
             gof_map = c("nobs", "adj.r.squared", "bic", "rmse")) |> 
  kable_styling(latex_options = c("scale_down"))
```

```{r}
#| label: prep-nested-logit

comparisons <- logits(answer = dichotomy(answer = c("Davankov",
                                                    "Spoiled ballot",
                                                    "Slutsky",
                                                    "Haritonov",
                                                    "Putin"),
                                         "Declined to answer"),
                      not_putin = dichotomy(opposition = c("Davankov",
                                                           "Spoiled ballot",
                                                           "Slutsky",
                                                           "Haritonov"),
                                            "Putin"),
                      opposition = dichotomy(
                        systemic = c("Slutsky", "Haritonov"),
                        nonsystemic = c("Davankov", "Spoiled ballot")),
                      nonsystemic = c("Spoiled ballot", "Davankov"),
                      systemic = c("Haritonov", "Slutsky"))

```

```{r}
#| label: nested-logit

m3.nested.naive <- nestedLogit(vote ~ sex + age_bin + time_to_vs.less_than_hour
                               + out_of_Russia_time + result_trust_bin, 
                               dichotomies = comparisons,
                               data = model_data, 
                               subset = model_data$vote != "Tore up/took"
                                        | !is.na(model_data$vote))

m3.nested.fe <- nestedLogit(vote ~ sex + age_bin + time_to_vs.less_than_hour
                            + out_of_Russia_time + result_trust_bin + as.factor(voting_station), 
                            dichotomies = comparisons,
                            data = model_data, 
                            subset = model_data$vote != "Tore up/took"
                            | !is.na(model_data$vote))

save(list = c("m3.nested.naive", "m3.nested.fe"), 
     file = here("scripts", "models", "nl_fe.RData"))
```

```{r}
#| label: tbl-nested-logit-naive
#| tbl-cap: "Nested logit results, naive approach"

models_m3.nested.naive <- models(m3.nested.naive, as.list = T)
names(models_m3.nested.naive) <- c("Don't answer vs answer", "Putin vs everyone", 
                                   "Non-systemic vs systemic opposition",
                                   "Spoiled vs Davankov", "Slutsky vs Haritonov")

modelsummary(models_m3.nested.naive, 
             output = "kableExtra", 
             stars = T,
             coef_map = coef_map_default) |> 
  kable_styling(latex_options = c("scale_down"))
```
```{r}
#| label: tbl-nested-logit-fe
#| tbl-cap: "Nested logit results, fixed effects"

models_m3.nested.fe <- models(m3.nested.fe, as.list = T)
names(models_m3.nested.fe) <- c("Don't answer vs answer", "Putin vs everyone", 
                                "Non-systemic vs systemic opposition",
                                "Spoiled vs Davankov", "Slutsky vs Haritonov")

modelsummary(models_m3.nested.fe, 
             output = "kableExtra", 
             stars = T,
             coef_map = coef_map_default) |> 
  kable_styling(latex_options = c("scale_down"))
```

